name: Deploy NGINX to AKS

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set AKS context using Azure CLI
      uses: azure/cli@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az aks get-credentials --resource-group app-grp --name example-aks1 --overwrite-existing

    - name: Deploy NGINX manifests
      run: |
        kubectl apply -f manifests/deployment.yaml --validate=false
        kubectl apply -f manifests/service.yaml --validate=false

    - name: Verify Deployment and Service
      run: |
        kubectl rollout status deployment/nginx-deployment
        kubectl get svc nginx-service
